updates: 
  - package-ecosystem: npm
    directory: /
    labels:
      - dependencies
    open-pull-requests-limit: 99
    schedule:
      interval: daily
      time: "06:00"
      timezone: Asia/Jakarta
    target-branch: main
    commit-message: 
      include: scope
      prefix: chore
    #reviewers: # NOTE: Edit this to your github username and then uncomment
    #  - Hazmi35
  - package-ecosystem: github-actions
    directory: /
    labels: 
      - gh-actions
      - dependencies
    open-pull-requests-limit: 99
    schedule: 
      interval: daily
      time: "06:00"
      timezone: Asia/Jakarta
    target-branch: main
    commit-message: 
      include: scope
      prefix: ci
    #reviewers: # NOTE: Edit this to your github username and then uncomment
    #  - Hazmi35
  - package-ecosystem: docker
    directory: "/"
    labels:
      - docker
      - dependencies
    open-pull-requests-limit: 99
    schedule:
      interval: daily
      time: "06:00"
      timezone: Asia/Jakarta
    target-branch: main
    commit-message:
      prefix: docker
      include: scope
    #reviewers: # NOTE: Edit this to your github username and then uncomment
    #- Hazmi35
version: 2